#! /usr/bin/env python

import math

def NFact(n):
    return math.factorial(n)

def twoN(n):
    return pow(2,n)

def N3(n):
    return n*n*n

def N2(n):
    return n*n

def sqrtN(n):
    return math.sqrt(n)

def NlogN(n):
    return n * math.log(n)

def N(n):
    return n

def K(n):
    return 1

def logN(n):
    return math.log(n)

def clamp(n):
    if n > 999999:
        return 999999
    return n;

for n in range(1,21):
    print "%1d,%f,%f,%f,%f,%f,%f,%f,%f,%f" % (
        clamp(n),
        clamp(NFact(n)),
        clamp(twoN(n)),
        clamp(N3(n)),
        clamp(N2(n)),
        clamp(NlogN(n)),
        clamp(N(n)),
        clamp(sqrtN(n)),
        clamp(logN(n)),
        clamp(K(n))
    )
